### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by lhunath** [fourplusone/observed-optional-object#1]
There does not appear to be any reason for why the class should be @available only on iOS 14+.

Please consider relaxing the @available rule to what is actually required by the implementation & in-line with 74aa40a398688b90ee7724797861185e5a696aca :–)

**Comment by fourplusone** [comment]
The implementation uses StateObject, which is only available on iOS 14+

**Comment by lhunath** [comment]
Would it be possible to use @State with a value-type Proxy to bring this to iOS 13?

**Comment by lhunath** [comment]
Proposal in #2

**Comment by fourplusone** [comment]
Providing an iOS 13 compatible variant requires a lot of workarounds which may impact performance and stability
